<?xml version="1.0" encoding="UTF-8"?>
<wsdl:definitions targetNamespace="http://demo.soap.tikkidinh.com" xmlns:apachesoap="http://xml.apache.org/xml-soap" xmlns:impl="http://demo.soap.tikkidinh.com" xmlns:intf="http://demo.soap.tikkidinh.com" xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/" xmlns:wsdlsoap="http://schemas.xmlsoap.org/wsdl/soap/" xmlns:xsd="http://www.w3.org/2001/XMLSchema">
<!--WSDL created by Apache Axis version: 1.4
Built on Apr 22, 2006 (06:55:48 PDT)-->
 <wsdl:types>
  <schema elementFormDefault="qualified" targetNamespace="http://demo.soap.tikkidinh.com" xmlns="http://www.w3.org/2001/XMLSchema">
   <element name="getWelcomeText">
    <complexType/>
   </element>
   <element name="getWelcomeTextResponse">
    <complexType>
     <sequence>
      <element name="getWelcomeTextReturn" type="xsd:string"/>
     </sequence>
    </complexType>
   </element>
  </schema>
 </wsdl:types>

   <wsdl:message name="getWelcomeTextRequest">

      <wsdl:part element="impl:getWelcomeText" name="parameters">

      </wsdl:part>

   </wsdl:message>

   <wsdl:message name="getWelcomeTextResponse">

      <wsdl:part element="impl:getWelcomeTextResponse" name="parameters">

      </wsdl:part>

   </wsdl:message>

   <wsdl:portType name="HelloSoap">

      <wsdl:operation name="getWelcomeText">

         <wsdl:input message="impl:getWelcomeTextRequest" name="getWelcomeTextRequest">

       </wsdl:input>

         <wsdl:output message="impl:getWelcomeTextResponse" name="getWelcomeTextResponse">

       </wsdl:output>

      </wsdl:operation>

   </wsdl:portType>

   <wsdl:binding name="HelloSoapSoapBinding" type="impl:HelloSoap">

      <wsdlsoap:binding style="document" transport="http://schemas.xmlsoap.org/soap/http"/>

      <wsdl:operation name="getWelcomeText">

         <wsdlsoap:operation soapAction=""/>

         <wsdl:input name="getWelcomeTextRequest">

            <wsdlsoap:body use="literal"/>

         </wsdl:input>

         <wsdl:output name="getWelcomeTextResponse">

            <wsdlsoap:body use="literal"/>

         </wsdl:output>

      </wsdl:operation>

   </wsdl:binding>

   <wsdl:service name="HelloSoapService">

      <wsdl:port binding="impl:HelloSoapSoapBinding" name="HelloSoap">

         <wsdlsoap:address location="http://localhost:8080/soap-example/services/HelloSoap"/>

      </wsdl:port>

   </wsdl:service>

</wsdl:definitions>
