CREATE TABLE Kayttajat (
	id SMALLINT NOT NULL AUTO_INCREMENT PRIMARY KEY,
	email VARCHAR(255) NOT NULL UNIQUE KEY,
	salasana VARCHAR(255) NOT NULL,
	suola VARCHAR(255) NOT NULL
) ENGINE=InnoDB DEFAULT CHARSET=latin1;